# Generated by Django 4.0.5 on 2022-06-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
