# Generated by Django 4.0.5 on 2022-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_stocksymbol_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stocksymbol',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_code_combination'),
        ),
    ]
